{% set name = "stereo-pipeline" %}

{% set version = "3.5.0_no_isis" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  git_url: git@github.com:NeoGeographyToolkit/StereoPipeline.git
  #url: https://github.com/NeoGeographyToolkit/StereoPipeline/archive/refs/tags/{{ version }}.tar.gz
  #sha256: 3e7b335eae875782f7110f8ffb2f2557720eff4221b6a952989f2c304d130596

build:
  number: 1
  skip: true  # [win]
  
requirements:
  build:
    - cmake >=3.15
    - make
    - c-compiler 1.8.0
    - cxx-compiler 1.8.0
    - fortran-compiler 1.8.0
    - {{ stdlib('c') }}
    - git
    - wget

  host:
    - libgdal
    - llvm-openmp
    - flann
    - openssl
    - libssh2
    - blas  # [linux]
    - blas 2.131 accelerate  # [osx]
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libopenblas
    - openblas
    - libopencv
    - opencv
    - proj
    - hdf5
    - libzlib
    - zlib
    - libboost-devel
    - libjpeg-turbo
    - libtiff
    - libpng
    - lz4-c
    - libstdcxx  # [linux]
    - libgcc  # [linux]
    - libcxx  # [osx]
    - chrpath  # [linux]
    - libglvnd  # [linux]
    - parallel
    - bzip2
    - pbzip2
    - krb5
    - pdal
    - libpdal-core
    - libpdal
    - ale
    - usgscsm
    - eigen
    - ceres-solver
    - cspice =67
    - csm >=3.0.3,<3.0.4
    - libcurl
    - curl
    - gflags
    - glog
    - geotiff
    - libprotobuf
    - protobuf
    - libxml2
    - mesalib
    - mysql
    - nlohmann_json
    - pcl 
    - python
    - python_abi
    - qhull
    - qt-main >=5.15,<5.16
    - qwt <6.3.0
    - suitesparse <5.11 # TheiaSfM fails with version 7
    - superlu <5.3 # likely need not enforce this
    - tbb
    - tbb-devel
    - xerces-c >=3.2.4,<3.3.0a0
    - armadillo
    - vlfeat
    - fftw
    - rocksdb
    - rapidjson
    - wget
    - embree >=3,<4
    - xorg-kbproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxi

  run:
    - libgdal
    - llvm-openmp
    - flann
    - openssl
    - libssh2
    - blas  # [linux]
    - blas 2.131 accelerate  # [osx]
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libopenblas
    - openblas
    - libopencv
    - opencv
    - proj
    - hdf5
    - libzlib
    - zlib
    - libboost-devel
    - libjpeg-turbo
    - libtiff
    - libpng
    - lz4-c
    - libstdcxx  # [linux]
    - libgcc  # [linux]
    - libcxx  # [osx]
    - chrpath  # [linux]
    - libglvnd  # [linux]
    - parallel
    - bzip2
    - pbzip2
    - krb5
    - pdal
    - libpdal-core
    - libpdal
    - ale
    - usgscsm
    - eigen
    - ceres-solver
    - cspice =67
    - csm >=3.0.3,<3.0.4
    - libcurl
    - curl
    - gflags
    - glog
    - geotiff
    - libprotobuf
    - protobuf
    - libxml2
    - mesalib
    - mysql
    - nlohmann_json
    - pcl 
    - python
    - python_abi
    - qhull
    - qt-main >=5.15,<5.16
    - qwt <6.3.0
    - suitesparse <5.11
    - superlu <5.3
    - tbb
    - tbb-devel
    - xerces-c >=3.2.4,<3.3.0a0
    - armadillo
    - vlfeat
    - fftw
    - rocksdb
    - rapidjson
    - wget
    - embree >=3,<4
    - xorg-kbproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxi

test:
  commands:
    - echo success
    - test -f $PREFIX/bin/hillshade  # [unix]

about:
  home: https://github.com/NeoGeographyToolkit/StereoPipeline
  summary: 'A suite of tools for producing terrain models published by NASA'
  description: |
    The NASA Ames Stereo Pipeline is a collection of tools for producing 3D terrain models from images acquired by satellites of planets and of Earth. It also supports alignment of terrains, correction of errors in camera positions and orientations, and structure from motion.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://stereopipeline.readthedocs.io/en/latest/index.html
  dev_url: https://stereopipeline.readthedocs.io/en/latest/building_asp.html

extra:
  recipe-maintainers:
    - oleg-alexandrov
